application: 
  port: 8080
database:
  host: "127.0.0.1"
  port: 5430
  username: "root"
  password: "secret"
  database_name: "news_letter" 
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"